/*
Write a program that will read a positive integer and determine and print its binary equivalent.
(Hint: The bits of the binary representation of an integer can be generated by repeatedly dividing the number and the 
successive quotients by 2 and saving the remainder, which is either 0 or 1, after each division.)
*/
#include<stdio.h>

int main(){
    int positive_integer,bits[64];
    printf("Enter a positive integer\n");
    scanf("%d",&positive_integer);
    for (int i = 0; i < 64; i++)
    {
        bits[i]=positive_integer%2;
        positive_integer/=2;
    }
    for (int i = 63; i>=0 ; i--)
    {
        printf("%d",bits[i]);
    }
    
    
    return 0;
}